export const TYPES = {
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  FETCH_TOPICS_REQUEST: 'FETCH_TOPICS_REQUEST',
  FETCH_TOPICS_SUCCESS: 'FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE: 'FETCH_TOPICS_FAILURE',
  FETCH_QUESTIONS_REQUEST: 'FETCH_QUESTIONS_REQUEST',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
  FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',
}

export const actions = {
  setNotifications: (bool) => ({ type: TYPES.SET_NOTIFICATIONS, bool }),
  fetchTopicsRequest: () => ({ type: TYPES.FETCH_TOPICS_REQUEST }),
  fetchTopicsSuccess: (response) => ({ type: TYPES.FETCH_TOPICS_REQUEST, response }),
}